# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake

# The command to remove a file.
RM = /nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/edant/dev/watcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/edant/dev/watcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Development\" \"Unspecified\" \"bin\" \"include\" \"san-bin\" \"test-bin\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/nix/store/x27c0x6982aj1ycrywlr7pl7piz3cqjj-cmake-3.25.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/edant/dev/watcher/CMakeFiles /Users/edant/dev/watcher//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/edant/dev/watcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wtr.hdr_watcher

# Build rule for target.
wtr.hdr_watcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.hdr_watcher
.PHONY : wtr.hdr_watcher

# fast build rule for target.
wtr.hdr_watcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.hdr_watcher.dir/build.make CMakeFiles/wtr.hdr_watcher.dir/build
.PHONY : wtr.hdr_watcher/fast

#=============================================================================
# Target rules for targets named wtr.watcher

# Build rule for target.
wtr.watcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.watcher
.PHONY : wtr.watcher

# fast build rule for target.
wtr.watcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.dir/build.make CMakeFiles/wtr.watcher.dir/build
.PHONY : wtr.watcher/fast

#=============================================================================
# Target rules for targets named wtr.watcher.asan

# Build rule for target.
wtr.watcher.asan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.watcher.asan
.PHONY : wtr.watcher.asan

# fast build rule for target.
wtr.watcher.asan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.asan.dir/build.make CMakeFiles/wtr.watcher.asan.dir/build
.PHONY : wtr.watcher.asan/fast

#=============================================================================
# Target rules for targets named wtr.watcher.msan

# Build rule for target.
wtr.watcher.msan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.watcher.msan
.PHONY : wtr.watcher.msan

# fast build rule for target.
wtr.watcher.msan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.msan.dir/build.make CMakeFiles/wtr.watcher.msan.dir/build
.PHONY : wtr.watcher.msan/fast

#=============================================================================
# Target rules for targets named wtr.watcher.tsan

# Build rule for target.
wtr.watcher.tsan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.watcher.tsan
.PHONY : wtr.watcher.tsan

# fast build rule for target.
wtr.watcher.tsan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.tsan.dir/build.make CMakeFiles/wtr.watcher.tsan.dir/build
.PHONY : wtr.watcher.tsan/fast

#=============================================================================
# Target rules for targets named wtr.watcher.ubsan

# Build rule for target.
wtr.watcher.ubsan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.watcher.ubsan
.PHONY : wtr.watcher.ubsan

# fast build rule for target.
wtr.watcher.ubsan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.ubsan.dir/build.make CMakeFiles/wtr.watcher.ubsan.dir/build
.PHONY : wtr.watcher.ubsan/fast

#=============================================================================
# Target rules for targets named wtr.test_watcher

# Build rule for target.
wtr.test_watcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.test_watcher
.PHONY : wtr.test_watcher

# fast build rule for target.
wtr.test_watcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/build
.PHONY : wtr.test_watcher/fast

#=============================================================================
# Target rules for targets named wtr.test_watcher.asan

# Build rule for target.
wtr.test_watcher.asan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.test_watcher.asan
.PHONY : wtr.test_watcher.asan

# fast build rule for target.
wtr.test_watcher.asan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/build
.PHONY : wtr.test_watcher.asan/fast

#=============================================================================
# Target rules for targets named wtr.test_watcher.msan

# Build rule for target.
wtr.test_watcher.msan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.test_watcher.msan
.PHONY : wtr.test_watcher.msan

# fast build rule for target.
wtr.test_watcher.msan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/build
.PHONY : wtr.test_watcher.msan/fast

#=============================================================================
# Target rules for targets named wtr.test_watcher.tsan

# Build rule for target.
wtr.test_watcher.tsan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.test_watcher.tsan
.PHONY : wtr.test_watcher.tsan

# fast build rule for target.
wtr.test_watcher.tsan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/build
.PHONY : wtr.test_watcher.tsan/fast

#=============================================================================
# Target rules for targets named wtr.test_watcher.ubsan

# Build rule for target.
wtr.test_watcher.ubsan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.test_watcher.ubsan
.PHONY : wtr.test_watcher.ubsan

# fast build rule for target.
wtr.test_watcher.ubsan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/build
.PHONY : wtr.test_watcher.ubsan/fast

#=============================================================================
# Target rules for targets named wtr.bench_watcher

# Build rule for target.
wtr.bench_watcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wtr.bench_watcher
.PHONY : wtr.bench_watcher

# fast build rule for target.
wtr.bench_watcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.bench_watcher.dir/build.make CMakeFiles/wtr.bench_watcher.dir/build
.PHONY : wtr.bench_watcher/fast

#=============================================================================
# Target rules for targets named snitch

# Build rule for target.
snitch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snitch
.PHONY : snitch

# fast build rule for target.
snitch/fast:
	$(MAKE) $(MAKESILENT) -f _deps/snitch-build/CMakeFiles/snitch.dir/build.make _deps/snitch-build/CMakeFiles/snitch.dir/build
.PHONY : snitch/fast

#=============================================================================
# Target rules for targets named snitch-header-only

# Build rule for target.
snitch-header-only: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snitch-header-only
.PHONY : snitch-header-only

# fast build rule for target.
snitch-header-only/fast:
	$(MAKE) $(MAKESILENT) -f _deps/snitch-build/CMakeFiles/snitch-header-only.dir/build.make _deps/snitch-build/CMakeFiles/snitch-header-only.dir/build
.PHONY : snitch-header-only/fast

src/wtr/bench_watcher/bench_concurrent_watch_targets.o: src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.o
.PHONY : src/wtr/bench_watcher/bench_concurrent_watch_targets.o

# target to build an object file
src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.bench_watcher.dir/build.make CMakeFiles/wtr.bench_watcher.dir/src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.o
.PHONY : src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.o

src/wtr/bench_watcher/bench_concurrent_watch_targets.i: src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.i
.PHONY : src/wtr/bench_watcher/bench_concurrent_watch_targets.i

# target to preprocess a source file
src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.bench_watcher.dir/build.make CMakeFiles/wtr.bench_watcher.dir/src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.i
.PHONY : src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.i

src/wtr/bench_watcher/bench_concurrent_watch_targets.s: src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.s
.PHONY : src/wtr/bench_watcher/bench_concurrent_watch_targets.s

# target to generate assembly for a file
src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.bench_watcher.dir/build.make CMakeFiles/wtr.bench_watcher.dir/src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.s
.PHONY : src/wtr/bench_watcher/bench_concurrent_watch_targets.cpp.s

src/wtr/test_watcher/test_concurrent_watch_targets.o: src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o
.PHONY : src/wtr/test_watcher/test_concurrent_watch_targets.o

# target to build an object file
src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o
.PHONY : src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o

src/wtr/test_watcher/test_concurrent_watch_targets.i: src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i
.PHONY : src/wtr/test_watcher/test_concurrent_watch_targets.i

# target to preprocess a source file
src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i
.PHONY : src/wtr/test_watcher/test_concurrent_watch_targets.cpp.i

src/wtr/test_watcher/test_concurrent_watch_targets.s: src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s
.PHONY : src/wtr/test_watcher/test_concurrent_watch_targets.s

# target to generate assembly for a file
src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s
.PHONY : src/wtr/test_watcher/test_concurrent_watch_targets.cpp.s

src/wtr/test_watcher/test_new_directories.o: src/wtr/test_watcher/test_new_directories.cpp.o
.PHONY : src/wtr/test_watcher/test_new_directories.o

# target to build an object file
src/wtr/test_watcher/test_new_directories.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_new_directories.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_new_directories.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_new_directories.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_new_directories.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_new_directories.cpp.o
.PHONY : src/wtr/test_watcher/test_new_directories.cpp.o

src/wtr/test_watcher/test_new_directories.i: src/wtr/test_watcher/test_new_directories.cpp.i
.PHONY : src/wtr/test_watcher/test_new_directories.i

# target to preprocess a source file
src/wtr/test_watcher/test_new_directories.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_new_directories.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_new_directories.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_new_directories.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_new_directories.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_new_directories.cpp.i
.PHONY : src/wtr/test_watcher/test_new_directories.cpp.i

src/wtr/test_watcher/test_new_directories.s: src/wtr/test_watcher/test_new_directories.cpp.s
.PHONY : src/wtr/test_watcher/test_new_directories.s

# target to generate assembly for a file
src/wtr/test_watcher/test_new_directories.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_new_directories.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_new_directories.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_new_directories.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_new_directories.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_new_directories.cpp.s
.PHONY : src/wtr/test_watcher/test_new_directories.cpp.s

src/wtr/test_watcher/test_simple.o: src/wtr/test_watcher/test_simple.cpp.o
.PHONY : src/wtr/test_watcher/test_simple.o

# target to build an object file
src/wtr/test_watcher/test_simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_simple.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_simple.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_simple.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_simple.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_simple.cpp.o
.PHONY : src/wtr/test_watcher/test_simple.cpp.o

src/wtr/test_watcher/test_simple.i: src/wtr/test_watcher/test_simple.cpp.i
.PHONY : src/wtr/test_watcher/test_simple.i

# target to preprocess a source file
src/wtr/test_watcher/test_simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_simple.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_simple.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_simple.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_simple.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_simple.cpp.i
.PHONY : src/wtr/test_watcher/test_simple.cpp.i

src/wtr/test_watcher/test_simple.s: src/wtr/test_watcher/test_simple.cpp.s
.PHONY : src/wtr/test_watcher/test_simple.s

# target to generate assembly for a file
src/wtr/test_watcher/test_simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_simple.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_simple.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_simple.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_simple.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_simple.cpp.s
.PHONY : src/wtr/test_watcher/test_simple.cpp.s

src/wtr/test_watcher/test_watch_targets.o: src/wtr/test_watcher/test_watch_targets.cpp.o
.PHONY : src/wtr/test_watcher/test_watch_targets.o

# target to build an object file
src/wtr/test_watcher/test_watch_targets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_watch_targets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_watch_targets.cpp.o
.PHONY : src/wtr/test_watcher/test_watch_targets.cpp.o

src/wtr/test_watcher/test_watch_targets.i: src/wtr/test_watcher/test_watch_targets.cpp.i
.PHONY : src/wtr/test_watcher/test_watch_targets.i

# target to preprocess a source file
src/wtr/test_watcher/test_watch_targets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_watch_targets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_watch_targets.cpp.i
.PHONY : src/wtr/test_watcher/test_watch_targets.cpp.i

src/wtr/test_watcher/test_watch_targets.s: src/wtr/test_watcher/test_watch_targets.cpp.s
.PHONY : src/wtr/test_watcher/test_watch_targets.s

# target to generate assembly for a file
src/wtr/test_watcher/test_watch_targets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.dir/build.make CMakeFiles/wtr.test_watcher.dir/src/wtr/test_watcher/test_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.asan.dir/build.make CMakeFiles/wtr.test_watcher.asan.dir/src/wtr/test_watcher/test_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.msan.dir/build.make CMakeFiles/wtr.test_watcher.msan.dir/src/wtr/test_watcher/test_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.tsan.dir/build.make CMakeFiles/wtr.test_watcher.tsan.dir/src/wtr/test_watcher/test_watch_targets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.test_watcher.ubsan.dir/build.make CMakeFiles/wtr.test_watcher.ubsan.dir/src/wtr/test_watcher/test_watch_targets.cpp.s
.PHONY : src/wtr/test_watcher/test_watch_targets.cpp.s

src/wtr/watcher/main.o: src/wtr/watcher/main.cpp.o
.PHONY : src/wtr/watcher/main.o

# target to build an object file
src/wtr/watcher/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.dir/build.make CMakeFiles/wtr.watcher.dir/src/wtr/watcher/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.asan.dir/build.make CMakeFiles/wtr.watcher.asan.dir/src/wtr/watcher/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.msan.dir/build.make CMakeFiles/wtr.watcher.msan.dir/src/wtr/watcher/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.tsan.dir/build.make CMakeFiles/wtr.watcher.tsan.dir/src/wtr/watcher/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.ubsan.dir/build.make CMakeFiles/wtr.watcher.ubsan.dir/src/wtr/watcher/main.cpp.o
.PHONY : src/wtr/watcher/main.cpp.o

src/wtr/watcher/main.i: src/wtr/watcher/main.cpp.i
.PHONY : src/wtr/watcher/main.i

# target to preprocess a source file
src/wtr/watcher/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.dir/build.make CMakeFiles/wtr.watcher.dir/src/wtr/watcher/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.asan.dir/build.make CMakeFiles/wtr.watcher.asan.dir/src/wtr/watcher/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.msan.dir/build.make CMakeFiles/wtr.watcher.msan.dir/src/wtr/watcher/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.tsan.dir/build.make CMakeFiles/wtr.watcher.tsan.dir/src/wtr/watcher/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.ubsan.dir/build.make CMakeFiles/wtr.watcher.ubsan.dir/src/wtr/watcher/main.cpp.i
.PHONY : src/wtr/watcher/main.cpp.i

src/wtr/watcher/main.s: src/wtr/watcher/main.cpp.s
.PHONY : src/wtr/watcher/main.s

# target to generate assembly for a file
src/wtr/watcher/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.dir/build.make CMakeFiles/wtr.watcher.dir/src/wtr/watcher/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.asan.dir/build.make CMakeFiles/wtr.watcher.asan.dir/src/wtr/watcher/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.msan.dir/build.make CMakeFiles/wtr.watcher.msan.dir/src/wtr/watcher/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.tsan.dir/build.make CMakeFiles/wtr.watcher.tsan.dir/src/wtr/watcher/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wtr.watcher.ubsan.dir/build.make CMakeFiles/wtr.watcher.ubsan.dir/src/wtr/watcher/main.cpp.s
.PHONY : src/wtr/watcher/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... snitch"
	@echo "... snitch-header-only"
	@echo "... wtr.bench_watcher"
	@echo "... wtr.hdr_watcher"
	@echo "... wtr.test_watcher"
	@echo "... wtr.test_watcher.asan"
	@echo "... wtr.test_watcher.msan"
	@echo "... wtr.test_watcher.tsan"
	@echo "... wtr.test_watcher.ubsan"
	@echo "... wtr.watcher"
	@echo "... wtr.watcher.asan"
	@echo "... wtr.watcher.msan"
	@echo "... wtr.watcher.tsan"
	@echo "... wtr.watcher.ubsan"
	@echo "... src/wtr/bench_watcher/bench_concurrent_watch_targets.o"
	@echo "... src/wtr/bench_watcher/bench_concurrent_watch_targets.i"
	@echo "... src/wtr/bench_watcher/bench_concurrent_watch_targets.s"
	@echo "... src/wtr/test_watcher/test_concurrent_watch_targets.o"
	@echo "... src/wtr/test_watcher/test_concurrent_watch_targets.i"
	@echo "... src/wtr/test_watcher/test_concurrent_watch_targets.s"
	@echo "... src/wtr/test_watcher/test_new_directories.o"
	@echo "... src/wtr/test_watcher/test_new_directories.i"
	@echo "... src/wtr/test_watcher/test_new_directories.s"
	@echo "... src/wtr/test_watcher/test_simple.o"
	@echo "... src/wtr/test_watcher/test_simple.i"
	@echo "... src/wtr/test_watcher/test_simple.s"
	@echo "... src/wtr/test_watcher/test_watch_targets.o"
	@echo "... src/wtr/test_watcher/test_watch_targets.i"
	@echo "... src/wtr/test_watcher/test_watch_targets.s"
	@echo "... src/wtr/watcher/main.o"
	@echo "... src/wtr/watcher/main.i"
	@echo "... src/wtr/watcher/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

