#! /usr/bin/env bash

lastdir=$PWD
cd "$(dirname "$0")/.." || exit 1
thisdir=$PWD
trap 'cd "$lastdir"' EXIT

echo "
[
{
  \"directory\": \"$thisdir\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++17 -c $thisdir/src/wtr/tiny_watcher/main.cpp\",
  \"file\": \"$thisdir/src/wtr/tiny_watcher/main.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++17 -o CMakeFiles/wtr.watcher.dir/src/wtr/watcher/main.cpp.o -c $thisdir/src/wtr/watcher/main.cpp\",
  \"file\": \"$thisdir/src/wtr/watcher/main.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++17 -o CMakeFiles/wtr.watcher.asan.dir/src/wtr/watcher/main.cpp.o -c $thisdir/src/wtr/watcher/main.cpp\",
  \"file\": \"$thisdir/src/wtr/watcher/main.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++17 -o CMakeFiles/wtr.watcher.tsan.dir/src/wtr/watcher/main.cpp.o -c $thisdir/src/wtr/watcher/main.cpp\",
  \"file\": \"$thisdir/src/wtr/watcher/main.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++17 -o CMakeFiles/wtr.watcher.ubsan.dir/src/wtr/watcher/main.cpp.o -c $thisdir/src/wtr/watcher/main.cpp\",
  \"file\": \"$thisdir/src/wtr/watcher/main.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.dir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.dir/devel/src/wtr/test_watcher/test_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.dir/devel/src/wtr/test_watcher/test_new_directories.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.dir/devel/src/wtr/test_watcher/test_simple.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_simple.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_simple.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.asan.dir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.asan.dir/devel/src/wtr/test_watcher/test_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.asan.dir/devel/src/wtr/test_watcher/test_new_directories.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.asan.dir/devel/src/wtr/test_watcher/test_simple.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_simple.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_simple.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.tsan.dir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.tsan.dir/devel/src/wtr/test_watcher/test_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.tsan.dir/devel/src/wtr/test_watcher/test_new_directories.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.tsan.dir/devel/src/wtr/test_watcher/test_simple.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_simple.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_simple.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.ubsan.dir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_concurrent_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.ubsan.dir/devel/src/wtr/test_watcher/test_watch_targets.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_watch_targets.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.ubsan.dir/devel/src/wtr/test_watcher/test_new_directories.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_new_directories.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.test_watcher.ubsan.dir/devel/src/wtr/test_watcher/test_simple.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_simple.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_simple.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/devel/include -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -std=gnu++20 -o CMakeFiles/wtr.bench_watcher.dir/devel/src/wtr/test_watcher/test_performance.cpp.o -c $thisdir/devel/src/wtr/test_watcher/test_performance.cpp\",
  \"file\": \"$thisdir/devel/src/wtr/test_watcher/test_performance.cpp\"
},
{
  \"directory\": \"$thisdir/build/out/this/Debug/_deps/snitch-build\",
  \"command\": \"/usr/local/bin/c++  -I$thisdir/build/out/this/Debug/_deps/snitch-src/include -I$thisdir/build/out/this/Debug/_deps/snitch-build -g -std=gnu++20 -o CMakeFiles/snitch.dir/src/snitch.cpp.o -c $thisdir/build/out/this/Debug/_deps/snitch-src/src/snitch.cpp\",
  \"file\": \"$thisdir/build/out/this/Debug/_deps/snitch-src/src/snitch.cpp\"
}
]"
