#! /usr/bin/env bash

LAST_DIR="$PWD"
cd "$(dirname "$0")/.." || exit 1
while read -r F
do
  clang-format -i "$F"
done \
  <<< "$(find devel/include src -type f -name '*.cpp' -or -name '*.hpp')"
cd "$LAST_DIR" || exit 1
