#! /usr/bin/env bash

PROJECT_ID='W973564ED9F278A21F3E12037288412FBAF175F889'

PROJECT_HONE_DIR="$(dirname "$0")/../devel"

PROJECT_HEADER="include/wtr/watcher.hpp"

# @todo This function doesn't work if the file doesn't end in a newline.
tool::hone() {
  USAGE="
  $0 < option > { option }

  option:
    --header-content-amalgam
    --header-content-raw
    --header-path-all
    --help

  example:
    tool/hone --header-content-amalgam > include/wtr/watcher.hpp"

  LAST_DIR="$PWD"

  cd "$(dirname "$0")/../devel" || return 1

  # Sanity checks
  while read -r H
  do if ! test -f "include/$H"
  then echo "Header file missing: 'include/$H'"; return 1; fi
  done <<< "$(
    cat "$PROJECT_HEADER" \
      | grep -E '([ ]*)#([ ]*)include ' \
      | sed -E 's/(([ ]*)#([ ]*)include )|(["<>])//g')"

  HEADER_PATH_ALL="$(\
    while read -r H
    do echo "$PWD/include/$H" || return 1
    done <<< "$(
      cat "$PROJECT_HEADER" \
        | grep -E '([ ]*)#([ ]*)include' \
        | sed -E 's/(([ ]*)#([ ]*)include )|(["<>])//g')"
  )"

  HEADER_CONTENT_RAW="$(\
    while read -r TOK
    do
      # cat the header, replace pragmas
      cat "include/$TOK" \
        | sed -E 's|(/\* )(@pragma/tool/hone/insert )(.+)( \*/)|\3 /\* @pragma/tool/hone/insert \*/|g'
    done <<< "$(
      cat "$PROJECT_HEADER" \
        | grep -E '(([ ]*)#([ ]*)include)|(pragma/tool/hone)' \
        | sed -E 's/(([ ]*)#([ ]*)include )|(["<>])//g')"
  )"

  HEADER_CONTENT_AMALGAM="$(\
    echo "#ifndef $PROJECT_ID" \
      && echo "#define $PROJECT_ID" \
      && echo "$HEADER_CONTENT_RAW" \
        | sed -E '/(#([ ]*)include [<"]wtr\/watcher.*)|(#([ ]*)include [<"]detail\/wtr.*)|(#pragma once)/d' \
      && echo "#endif /* $PROJECT_ID */" \
  )"

  if test -n "$*"
  then
    if echo "$*" | grep -q -- --header-content-amalgam
    then echo "$HEADER_CONTENT_AMALGAM"; fi
    if echo "$*" | grep -q -- --header-content-raw
    then echo "$HEADER_CONTENT_RAW"; fi
    if echo "$*" | grep -q -- --header-path-all
    then echo "$HEADER_PATH_ALL"; fi
    if echo "$*" | grep -q -- --help
    then echo "$USAGE"; fi
  else
    echo "$USAGE"
  fi

  cd "$LAST_DIR" || return 1
}

tool::hone $@
exit $?
