#! /usr/bin/env bash

LAST_DIR="$PWD"
cd "$(dirname "$0")/.." || exit 1
echo "\
lines of code: $(tool/sloc)
lines of documentation: $(tool/slod)
ratio of code to documentation: $(echo "scale=1; $(tool/sloc)/$(tool/slod)" | bc)"
cd "$LAST_DIR" || exit 1

