#! /usr/bin/env bash

LAST_DIR="$PWD"
EC=1
cd "$(dirname "$0")/.." \
  || exit 1
if which cloc &> /dev/null \
  && which jq &> /dev/null
then
  cloc src/test_watcher devel/include/test_watcher --json \
    | jq '."C/C++ Header"."code" + ."C++"."code"'
else
  echo please install cloc and jq
  EC=1
fi
cd "$LAST_DIR" \
  || exit 1
exit $EC
