#! /usr/bin/env bash

LAST_DIR="$PWD"
cd "$(dirname "$0")/.." \
  || exit 1
if which -s cloc \
  && which -s jq
then
  SLOC="$(\
    cloc README.md src include --json \
      | jq '."C/C++ Header"."code" + ."C++"."code"')"
  SLOD="$(\
    cloc README.md src include --json \
    | jq '."Markdown"."code" + ."C/C++ Header"."comment" + ."C++"."comment"')"

  echo "significant lines of code: $SLOC"
  echo "lines of documentation: $SLOD"
else
  echo please install cloc and jq
fi
cd "$LAST_DIR" \
  || exit 1
