#! /usr/bin/env bash

LAST_DIR="$PWD"
EC=0
cd "$(dirname "$0")/.." \
  || exit 1
if which -s cloc \
  && which -s jq
then
  cloc README.md src include --json \
    | jq '."Markdown"."code" + ."C/C++ Header"."comment" + ."C++"."comment"'
else
  echo please install cloc and jq
  EC=1
fi
cd "$LAST_DIR" \
  || exit 1
exit $EC
