#! /usr/bin/env bash

IGNORE_GLOB="\
security.md\
|license\
|readme.md\
|changelog.md\
|contributing.md\
|SECURITY.md\
|LICENSE\
|README.md\
|CHANGELOG.md\
|CONTRIBUTING.md\
|test_watcher\
|tool\
|this\
|notes.md\
|artifacts.txt\
|compile_commands.json\
|Dockerfile\
|Containerfile\
|CMakeLists.txt\
|conanfile.txt\
|cmake\
|flake.nix\
|flake.lock\
|portable-destructive-rename\
|etc\
|result\
|container-devel\
|WORKSPACE\
|BUILD.bazel"

(
  cd "$(dirname "$0")/.." || exit 1
  exa \
    . \
    --tree \
    --level 100 \
    --ignore-glob="$IGNORE_GLOB" \
    --sort type \
    --reverse \
    | tail -n +1
)
