#! /usr/bin/env bash

lastdir=$PWD
cd "$(dirname "$0")/../.." || exit 1 ; trap 'cd "$lastdir"' EXIT
[ ! -d build/tmp ] && mkdir -p build/tmp ; cd build/tmp || exit 1
if [ -f ../out/this/Release/wtr.watcher ]
then ../out/this/Release/wtr.watcher . -ms 1500 &
else
  nix build
  nix run .\#watcher build -L -- . -ms 1500 &
fi
sleep 0.8 # Be sure we didn't pick up any events from `mkdir`
touch a
mv a b
wait
rm b
