#! /usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
[ -f compile_commands.json ] && exit 0
npx node-gyp configure --release -- -f gyp.generator.compile_commands_json.py
cp build/Release/compile_commands.json .
