# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task build_shared_library: ["lib"] do
  framework_deps = case RbConfig::CONFIG["host_os"]
  when /darwin/
    "-framework CoreServices -framework CoreFoundation"
  else
    ""
  end
  version = File.read("../.version").strip
  libname = "libwatcher-c-#{version}.so"
  sh "c++ -shared -std=c++17 -O2 #{framework_deps} ../watcher-c/src/watcher-c.cpp -I ../watcher-c/include -o lib/#{libname}"
end

task default: [:clobber, :build_shared_library, :spec]
