# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task build_shared_library: ['lib'] do
  case RbConfig::CONFIG['host_os']
  when /darwin/
    framework_deps = '-framework CoreServices -framework CoreFoundation'
    link_rpath = '-Wl,-rpath,/usr/local/lib'
  else
    framework_deps = ''
    link_rpath = ''
  end
  version = File.read('../.version').strip
  libname = "libwatcher-c-#{version}.so"
  sources = '../watcher-c/src/watcher-c.cpp'
  includes = '../watcher-c/include'
  sh "c++ -shared -std=c++17 -O2 #{framework_deps} #{sources} -I #{includes} -o lib/#{libname} #{link_rpath}"
end

task default: %i[clobber build_shared_library spec]
