name: Test (Go)

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false
      - run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          sudo cmake --install build
      - run: go test -race
        working-directory: watcher-go
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: watcher-go
